name: ARM Logic App Deploy

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  LogicAppDeploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.SP_SECRET}}
    - name: Azure Key Vault Action
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyVault: "logicapp-demo"
        secrets: 'clientId, subscriptionId'
      id: mysecrets
    - run: echo ${{steps.mysecrets.output.clientId}}
           echo ${{steps.mysecrets.output.subscriptionId}}
    - name: replace tokens
      uses: falnyr/replace-env-vars-action@master
      with:
       filename: ./test.txt    
     
        
        
#     - run: ls
#       shell: powershell
#       working-directory: ${{github.workspace}}
#     - name: Deploy Azure Resource Manager (ARM) Template
#       uses: Azure/arm-deploy@v1.0.8
#       with:
#         scope: resourcegroup
#         resourceGroupName: logicapp
#         template: ./ARM-templates/logicapp.json
        
    
    
    
      
