name: ARM Logic App Deploy

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  LogicAppDeploy:
    runs-on: windows-latest
    
    steps:
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.SP_SECRET}}
    - run: pwd
      shell: powershell
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.8
      with:
        scope: resourcegroup
        resourceGroupName: logicapp
        template: './ARM-templates/logicapp.json'
        
    
    
    
      
