name: Build and deploy mars logic app
on:
  workflow_dispatch:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
jobs:
  logicappbuild:
    name: build
    #runs-on: [Enterprise, self-hosted, Linux, X64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: marslogicapp
        # A file, directory or wildcard pattern that describes what to upload
        path:  ./ARM-templates
    

